### ISSUE TITLE
BTTether not connecting

### ISSUE THREAD

**Issue by kamal-masarweh** [lbdroid/JoyingIntelStuff#4]
I've been using this app since I have the Joying unit and it has been very helpful.
The issue is that sometimes the process is not automated. I'm assuming is it because I don't have bluetooth always turned on, and it seems that bluetooth tethering isn't turned on in time when connection is done.

I read about this limitation in the description of the APK on XDA.

Is there a solution for that? 

Thanks

**Comment by lbdroid** [comment]
What, on your phone you mean?
I suppose that is *possible*, but it should be pretty fast. If the problem is on your phone side, then you can fix it very simply by *not turning bluetooth off*.

The reason you sometimes see it not automatically connecting, is because it *does* connect automatically, and then the jerking resets its bluetooth. I've been mulling over the idea of adding a reconnect to it, but the problem is that for that to work, it would have to be a persistently running service rather than just responding to intents.

FWIW: Using MCUController+++ instead of the factory jerking software results in the car radio bluetooth auto-reset being eliminated, allowing for a much more reliable connection.

**Comment by kamal-masarweh** [comment]
I see
What is MCUController+++?
